#pragma once
const int WELCOME_SCREEN_INDEX = 0;
const int LEVEL_EDITOR_SCREEN_INDEX= 1;
const int DESKTOP_APP_EDITOR_SCREEN_INDEX = 2;
const int MOBILE_APP_EDITOR_SCREEN_INDEX = 3;
const int GUI_EDITOR_SCREEN_INDEX = 4;
const int ANIMATION_EDITOR_SCREEN_INDEX = 5;
