// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_DSUSTRING_SQUAREBOX_DSUSTRING_H_
#define FLATBUFFERS_GENERATED_DSUSTRING_SQUAREBOX_DSUSTRING_H_

#include "flatbuffers/flatbuffers.h"

namespace SquareBox {
namespace DSUString {

struct SquareBoxStringData;
struct SquareBoxStringDataBuilder;

struct SquareBoxStringData FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef SquareBoxStringDataBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DATA = 4
  };
  const flatbuffers::String *data() const {
    return GetPointer<const flatbuffers::String *>(VT_DATA);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_DATA) &&
           verifier.VerifyString(data()) &&
           verifier.EndTable();
  }
};

struct SquareBoxStringDataBuilder {
  typedef SquareBoxStringData Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_data(flatbuffers::Offset<flatbuffers::String> data) {
    fbb_.AddOffset(SquareBoxStringData::VT_DATA, data);
  }
  explicit SquareBoxStringDataBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<SquareBoxStringData> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<SquareBoxStringData>(end);
    return o;
  }
};

inline flatbuffers::Offset<SquareBoxStringData> CreateSquareBoxStringData(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> data = 0) {
  SquareBoxStringDataBuilder builder_(_fbb);
  builder_.add_data(data);
  return builder_.Finish();
}

inline flatbuffers::Offset<SquareBoxStringData> CreateSquareBoxStringDataDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *data = nullptr) {
  auto data__ = data ? _fbb.CreateString(data) : 0;
  return SquareBox::DSUString::CreateSquareBoxStringData(
      _fbb,
      data__);
}

inline const SquareBox::DSUString::SquareBoxStringData *GetSquareBoxStringData(const void *buf) {
  return flatbuffers::GetRoot<SquareBox::DSUString::SquareBoxStringData>(buf);
}

inline const SquareBox::DSUString::SquareBoxStringData *GetSizePrefixedSquareBoxStringData(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<SquareBox::DSUString::SquareBoxStringData>(buf);
}

inline bool VerifySquareBoxStringDataBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<SquareBox::DSUString::SquareBoxStringData>(nullptr);
}

inline bool VerifySizePrefixedSquareBoxStringDataBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<SquareBox::DSUString::SquareBoxStringData>(nullptr);
}

inline void FinishSquareBoxStringDataBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<SquareBox::DSUString::SquareBoxStringData> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedSquareBoxStringDataBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<SquareBox::DSUString::SquareBoxStringData> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace DSUString
}  // namespace SquareBox

#endif  // FLATBUFFERS_GENERATED_DSUSTRING_SQUAREBOX_DSUSTRING_H_
